#!/usr/bin/env bash

###################################################################
# Script Name	  : rpi_3d_printer_config_backuper.sh
# Description	  : Sets up your raspberry pi to be connected with Github to auto backup your printer config files.
# Author       	: Landon Patmore
# Email         : landon.patmore@gmail.com
# License       : MIT
###################################################################

PERSONAL_TOKEN="$1"
GITHUB_USERNAME="$2"
GITHUB_EMAIL="$3"
GITHUB_NAME="$4"
PRIVATE_REPO="$5"
RASPBERRY_PI_USERNAME="$7"
REPO_NAME="3d-printer-config-files"
DESCRIPTION="This repository was generated by LandonPatmore's 3d_printer_config_backuper script located at: https://github.com/LandonPatmore/3d-printer-config-backuper"
PUBLIC_SSH_KEY=""

printf "Setting git email..."
git config --global user.email "$GITHUB_EMAIL"
printf "Set"

printf "\n\n"

printf "Setting git name..."
git config --global user.name "$GITHUB_NAME"
printf "Set"

printf "\n\n"

printf "Generating SSH key..."
ssh-keygen -q -t rsa -N '' -b 4096 -f /home/"$RASPBERRY_PI_USERNAME"/.ssh/id_rsa -C "$GITHUB_EMAIL"
printf "Generated"

printf "\n\n"

printf "Starting SSH agent..."
eval "$(ssh-agent -s)" >/dev/null 2>&1
printf "Started"

printf "\n\n"

printf "Adding private SSH key to SSH agent..."
ssh-add -k "/home/$RASPBERRY_PI_USERNAME/.ssh/id_rsa"
printf "Added"

printf "\n\n"

printf "Grabbing SSH public key..."
PUBLIC_SSH_KEY="$(<"/home/$RASPBERRY_PI_USERNAME/.ssh/id_rsa.pub")"
printf "Grabbed"

printf "\n\n"

printf "Uploading SSH key to Github..."
curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: token $PERSONAL_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/user/keys \
  -d "{\"title\":\"Git SSH key\",\"key\":\"$PUBLIC_SSH_KEY\"}" \
#  -S -s -o /dev/null
printf "Uploaded"

printf "\n\n"

printf "Generating Github repo..."

curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: token $PERSONAL_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/user/repos \
  -d "{\"name\":\"$REPO_NAME\",\"description\":\"$DESCRIPTION\", \"private\":\"$PRIVATE_REPO\"}" \
#  -S -s -o /dev/null
printf "Generated"

printf "\n\n"

printf "Backing up printer config files..."
printf "\n"
cp -ar "$PRINTER_CONFIG_PATH" "/home/$RASPBERRY_PI_USERNAME/printer_config_backup"
printf "Backed up"

printf "\n\n"

printf "Pushing files to Github..."
cd "$PRINTER_CONFIG_PATH" || exit

git init
git add .
git commit -m "Initial push of printer config files"
git branch -M master
git remote add origin git@github.com:"$GITHUB_USERNAME"/"$REPO_NAME".git
git push -u origin master
printf "Pushed"

printf "
Deleting myself, goodbye!
"

